### ISSUE TITLE
Fetch Proposal context from Litentry graph

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#1079]

**Comment by geastwood** [comment]
IMO, having Polkassembly integrated in `Litentry Graph` would not be optimal, at least in current architecture of `Litentry Graph`. Because it's too specific a service. It would be ideal that Polkassembly data can be designed as an extension to `Litentry Graph`, which is able to plug in easily without forcing parties who are running `Litentry Graph` to setup for Polkassembly.

**Quick Context**

`Litentry Graph` is designed to in long term to let other parties to run the OS solution to become a data provider to index data and provide data via graphql layer. It would be less ideal that we force them to setup all small services, e.g. Polkassembly. Only if they find a particular adapter/extension useful, they can set it up.

**Comment by stephanie-olp** [comment]
The relevancy of this issue depends on this [issue](https://github.com/litentry/litentry-app/issues/1141)

**Comment by silva-fj** [comment]
We are already getting the context of proposals (title, description) from Subsquare
