### ISSUE TITLE
Research: Hydra

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-app#243]
A service might be helpful for both our native app and web app

https://github.com/Joystream/hydra

@Kailai-Wang has already checkout the repo and experimented with it, let him give you (@franjs) an update/intro.

**Comment by geastwood** [comment]
This may ofc need helps from DevOps team.

**Comment by Kailai-Wang** [comment]
Hi @franjs , as @geastwood mentioned, I already did some research / trial run of hydra to some extent, I have documented what I have done here:
https://www.notion.so/litentry/subpage-researches-and-notes-of-hydra-WIP-60285e4f23f049998dc1d163a83aca14

You could read it and feel free to ask me if you have any problems.
Alternatively we could arrange a meeting if you feel necessary.

**Comment by silva-fj** [comment]
> Hi @franjs , as @geastwood mentioned, I already did some research / trial run of hydra to some extent, I have documented what I have done here:
> 
> https://www.notion.so/litentry/subpage-researches-and-notes-of-hydra-WIP-60285e4f23f049998dc1d163a83aca14
> 
> 
> 
> You could read it and feel free to ask me if you have any problems.
> 
> Alternatively we could arrange a meeting if you feel necessary.

Awesome, I will take a look. Thank you 👍

**Comment by silva-fj** [comment]
Hydra separates data ingesting and indexing (done by Hydra Indexer) and processing (done by Hydra Processor)

The **indexer** stores **events** and **extrinsics**. It uses [TypeORM](https://github.com/typeorm/typeorm) to interact with the database in both the indexer and the indexer gateway.

The indexer gateway is built using [Warthog](https://github.com/goldcaddy77/warthog) library. Most of the code is generated by the library which could make it a bit awkward to add custom code, but it seems possible. However, according to the docs **_"Hydra Indexer + API gateway is a set-and-forget service which requires maintainance only when there is a major runtime upgrade."_**, so since the indexer's job is to store the data from the chain as it is, there is probably no reason to add custom logic there.  But It is possible to inject custom types and type overrides for spec, chain and bundle definitions.

In the Processor is where all our business logic would go, the documentation is not very good but it does not seem too complex. First one need to create a schema file which describes the domain objects, relationships and the supported queries (it can be generated with the hydra-cli), and add what they call mappings which are the event handlers (the code that transforms the data coming from the indexer and stores it in the DB). All these needs to be defined in the Query Node Manifest (a config file to generate the models, types, etc). Then with the cli the code for the graphql API (the one that our apps will consume) can be generated.

The benefits of using a service like this are many, for example:

- Reduce complexity in the clients
- Improve performance
- Adds search/filtering/pagination (server side) capabilities.
- Reduce over fetching
- Sometimes the ws connections are not stable, this reduces the chances of having this kind of problems.
