### ISSUE TITLE
Indexer

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#347]

**Comment by silva-fj** [comment]
Notes on the indexer POC for the mobile app (tips module):

No all data can be indexed since some depend on a current on-chain value, for example the BestNumber (current/latest block number) is needed to calculate the remaining time until the proposed tip closes. This means that we would need to interact with the api instance and have some logic in the app anyways.

Another point is that some data needs to be updated on some events. For example after a tip proposal closes, the status needs to be changed (only the open tips are displayed in the apps), so to model the data correctly and keep it up to date, it would not be as simple as just transform and save it In the database (so no mongodb), we need to understand the relations the data has as well as how the data can change and know all the events that make them change.

It is probably not likely that we will need to search for old (closed) tips, and since some logic still needs to live in the apps I think it’s a good idea to have an api where we can fetch the data the apps need regardless of whether the data is indexed or coming directly from the chain.
