### ISSUE TITLE
Feature: Log into Polkassembly

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#544]
- [ ] Technical question: how to enable users to log into their Polkassembly account within our app? 

2 use cases where the user will be asked to log into his polkassembly account:
- When he wants to create a new thread
- When he wants to interact in an existing conversation

**Comment by stephanie-olp** [comment]
Discuss this with @mikuczi

**Comment by stephanie-olp** [comment]
Hey @franjs, Do you think you can write down on this ticket the different ways to log into Polkassembly (from the technical side)?
So @mikuczi can have a look whenever he has some time

**Comment by silva-fj** [comment]
> Hey @franjs, Do you think you can write down on this ticket the different ways to log into Polkassembly (from the technical side)? So @mikuczi can have a look whenever he has some time

From the app we can [sign-up](https://polkadot.polkassembly.io/signup) and [login](https://polkadot.polkassembly.io/login) with web3 address. The process is similar to how we do transactions in the app. The user needs to select an address, then "confirm" that she/he wants to connect to Polkassembly (here we just sign a message we get from the api so they can verify that the user is the owner of the address), then we get an access token we can use to make requests to interact with Polkassembly. The difference to how it works on the Polkassembly website is that instead of using the browser extension to sign the message we will sign the message with the mechanisms we have in our app.

**Comment by stephanie-olp** [comment]
Beforehand: Discuss about the "account-view" in the app

**Comment by stephanie-olp** [comment]
Not relevant anymore, as we might work with Subsquare  in the near future more than PolkAssembly
