### ISSUE TITLE
Improve UX for password creation to encrypt exported data

### ISSUE THREAD

**Issue by stephanie-olp** [litentry/litentry-app#730]
> "As a user, I'm confused about what the password field is used for on the `Export account` screen. The initial impression is that I have to input the password that I chose when creating the account in order to authorize the action for exporting the account. However, I find out, the true use case of the password field is actually to encrypt the content of the exported data.
Therefore I would suggest that we explicitly let the user know about this information. "

Mockup for export account screen:
<img src="https://user-images.githubusercontent.com/85941267/147191360-45b3e0fd-5d98-4b77-8ad3-2f9926bf3405.png" width="275" height="600">

**Comment by ishrak-imam** [comment]
While checking the existing code in `ExportAccountWithJsonFileScreen` it seems like the password is not used for encrypting the content of the exported data. In fact the password is not being used for anything. Whenever we retrieve an account from `react-native-substrate-sign` it gives and encoded value which is actually the encoded string that can be used for importing an account from json. The exported json looks like following:

polkadot js extension
```
{
  "encoded":"mCwlJTZ3pUTEvUBVn8B62uz1QhWH4AHNzdOhrHcwsn4AgAAAAQAAAAgAAACK9ZAMV9t8vPG3VMyH2oCzLVlKyE15Y0Okp9mcAPUzxn2LHUfBmoiw83/lsZlfv1taJQX2RygwJSZ8WGr+xcluxynJ4/EATrYJfQrFpHMXXv4OSbqYVqapQ+gd90KSB5cOO/VVTRPZmy+rdOWiOL+K13v28gMAC+Fq8Byehxi+ITa6XMYM5T/8qCWpl9DFZke50442N+Dqrc/r0yAR",
  "encoding":{
    "content":[
      "pkcs8",
      "sr25519"
    ],
    "type":[
      "scrypt",
      "xsalsa20-poly1305"
    ],
    "version":"3"
  },
  "address":"5F6ekUuuwHbmTtkbR4UNyST5YPCcUrRnLkihaYRCxFLn4cAH",
  "meta":{
    "genesisHash":"0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
    "isHidden":false,
    "name":"Polka_PNS",
    "whenCreated":1637179943351
  }
}
```

react-native-substrate-sign
```
{
  "address":"16LoVQGVjabJx49hTz8XCE25XVnPcxuJ5JAeAFD1qraHeUWm",
  "encoded":"{\"cipher\":\"aes-128-ctr\",\"cipherparams\":{\"iv\":\"d7dbab9cabe462c9ec98a1855d0b5d4f\"},\"ciphertext\":\"8f0ec0000ae9703be8fe5fdf6b50c6f6006c0f6008b4e70d6cd18a3ff5d85e01d334ff5ff35eb5445459adbdbcb1c8db89f595321abe8ab3b1c6be97ae493425b73081b9b8e0b7a238ac8c5858ee867f9a02\",\"kdf\":\"pbkdf2\",\"kdfparams\":{\"c\":10240,\"dklen\":32,\"prf\":\"hmac-sha256\",\"salt\":\"f1995095d9ee656c925160128b8108d0d8fa86fad1bb1f2d86ce86d7167d13a9\"},\"mac\":\"25a856d0eb9ee5ed3992907012b2bfcc7ba5a26a48948bd2893c8efdc9e365a6\"}",
  "meta":{
    "name":"Name",
    "network":"polkadot",
    "isFavorite":false
  },
  "isExternal":false
}
```
In polkadot js extension when exporting an account it needs the original password to actually retrieve the account from keyring and make a json out of it since it uses a wrapper package named `ui-keyring` but `react-native-substrate-sign` is different from that.

Encrypting this json content again seems like an unnecessary redundancy. However, we can modify the UX accordingly.
cc @geastwood

**Comment by ahoseinian** [comment]
Yes we don't need to use the password here because we already have the encrypted data in our account context. however I think it's a good idea to get the password from the user here, make sure it is correct and then export the account just to make sure user knows the account password correctly. this way it can prevent confusions when trying to import the account again.
