### ISSUE TITLE
Preliminary discussion on goal and vision alignement

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-app#816]
This is a follow-up discussion after our pre-kickoff meeting on 25.01.2022.

For 2021, IMO we have laid a really good foundation going forward, both technically and team-wise. 

As @lmdobreva  mentioned we should think about our goal. @lmdobreva probably can add belong why having clear goal are important and what to consider when we are defining them.

As for products, my thinking can be divided into 3 main points

1. scope and carry out features for governance, really to add value for users who are regularly participating on-chain governance
2. internalize and create synergy with Litentry's products. e.g. MCP, Drop3
3. since we are also a wallet provider, we should take advantage of this fact and integrate services like **WalletConnect** and **beacon SDK**.

## Action points
* Feel free to write a small reflection
* outline your opinion on how we move forward

This issue (content within this discussion) will serve as a basis for our 2022 Kickoff, provide guidance for the mobile app's roadmap for 2022.

**Comment by lmdobreva** [comment]
Based on our discussion last Friday, here are my thoughts, as organised as possible: 

## Problem
 On-chain governance is still a niche activity and participation requires effort and knowledge while providing minimal or no incentives to users. 

## Vision
Make on-chain governance participation a popular activity for all users (at least users of all substrate-based networks)

## How

- Educate users so they have all the knowledge and insights needed to participate in on-chain governance

> Educational content
> Relevant News and updates
> Enable Discussions

- Engage users so they have a variety of ways to do so

> Easy to use overview, actions, integrations
> Reminders, Push Notifications, Widgets, etc
> Recommendations 
> Gamify participation

- Provide clear benefits 

> Use behaviour data to enrich Identity (functional benefit)
> Recognise participation (psychological benefit, social benefit)
> Reward participation (financial benefit)

## How does it relate to Litentry

We help drive up on-chain governance adoption and by doing so we encourage users to enrich their identity with this information on MCP for example. We could also let them use this information in combination with Drop3 campaigns.

Rough thoughts here. What do you think?

**Comment by hanwencheng** [comment]
summarize my opinions a bit on today's meeting:

* Focus on governance will gain more adoption and a good position. A mobile app for all litentry products is hard in design, not an easy task.
* Educational tasks are of higher priority as it is important to onboard new community members, also because the on-chain governance participation is not good ATM.
* communication is important when we revise the milestones.
* Focus on Conviction Voting will highlight the product among others, translation is important, once the internal design is done, we could start discussing with Polkadot community and councilors about the requirement and revise the design, make sure we are translating it in a nice way.
* Remove "litentry" in the app name but remain the logo unchanged.
* The app is an entry for all Litentry related products to the Polkadot community.

**Comment by stephanie-olp** [comment]
Here is a summary of the discussion we had about the milestones and the vision of the app

### Our Target Audience

Large audience instead of only councils

### Our Goal

Make the governance more popular by onboarding more members and increasing participation. In the future we would like the app to be a gateway to our other products

### How?

Make the app more educational and give incentives and reasons to push people to participate. 

### How flexible toward the original proposal?

There can be potential frictions if we want to change the original proposition but everything is about communicating properly with the councils and the community. If we want to change the milestones, we should first identify which points? And how? Once we have clear answers on these questions, we can introduce our new ideas to the councils and get their approval
Start to look into how to translate conviction voting into our app: if we are the first to do it, it can be big deal for us

### Our Next Step
* Change the name of the app to something more governance-related as it is misleading people on the purpose of the app (https://github.com/litentry/litentry-app/issues/856)
* Answer to the following questions:
  - How to make the topic of governance more accessible ? 
  - Which incentives can be given to push people to more actively participate in governance ? 
  - What changes has to be done if Conviction Voting is implemented ? (https://github.com/litentry/litentry-app/issues/861)
* Once these questions are answer come up with an updated version of the Milestones and introduce them to the councils
