### ISSUE TITLE
Bug: can't enable notifications after disabling

### ISSUE THREAD

**Issue by hanwencheng** [litentry/litentry-app#898]
> I can't enable notifications after initially disabling them. It works if you reinstall, but I think that might be a bug. 

Get this feedback from Raul, confirmation needed.

App version:

## Steps To Reproduce

1.
2.

Link or media file of the bug:

**Comment by silva-fj** [comment]
@hanwencheng do you know if it is on IOS? If by "disabling" he means pressing "Don't allow" when the native alert asking for permissions is prompted then there is nothing we can do in the app. 

That's why we have the following message in the footer of the screen:

<img width="360" alt="Screenshot 2022-02-21 at 2 32 39 PM" src="https://user-images.githubusercontent.com/8374946/154965323-bfb4e528-6410-41f7-9a20-5bcf9704fda6.png">

**Comment by ishrak-imam** [comment]
@franjs 
I think the issue here is, once the permission is skipped initially, there is now way to prompt for a system level permission later. What we can do is prompt the system level dialog in the notification settings screen if the user wants to enable PN and has skipped initially.

**Comment by silva-fj** [comment]
Yes, this can also be the case. We should trigger the custom prompt again in the notification settings screen if it was skipped the first time.

**Comment by hanwencheng** [comment]
Would that be annoying if a user disables it on purpose because he/she does not want to accept PN?

**Comment by Ekaanth** [comment]
@hanwencheng  With the current fix, then the user hasn't enabled notification initially but enables information later, it will provide a notification alert, like this:

![Simulator Screen Shot - iPhone 12 - 2022-02-22 at 09 58 14](https://user-images.githubusercontent.com/22363352/155121775-77e385b7-dd6c-4508-925f-049e3725f0b1.png)

**Comment by silva-fj** [comment]
> Would that be annoying if a user disables it on purpose because he/she does not want to accept PN?

Yep, but I think we are referring to different things. One thing is the permissions prompt and another thing is the settings that we have to enable/disable the specific notifications. On IOS we need to ask for permission to receive PN and if the user presses "Don't allow", then there is no way the user can change that from within the app, to allow PN one needs to change the notifications settings in the phone. For this reason is a common practice to have a custom pre-permission screen to ask the user if he/she wants to enable push notifications before showing the native prompt. In this pre-permissions screen the user can "Skip" the decision for later but currently we don't have a way to re-trigger that if the user has skipped it.
