### ISSUE TITLE
Bug: Error when signing with latest Parity Signer

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-app#902]
App version:

## Steps To Reproduce

1. init a transfer from an external wallet (account is in parity signer)
2. when scanning the signature, received the following error (in screenshot) in parity signer.

Link or media file of the bug:
![IMG_0006](https://user-images.githubusercontent.com/1623359/155094034-c5f65e4d-7980-4fca-87d3-c7173e561c6a.PNG)

## The current behavior
stucked in error screen within Parity app

## The expected behavior
should work, or at least show with which metadata is the payload is prepared from Litentry app

**Comment by geastwood** [comment]
After some digging it seems that our ApiClient construct the raw tx with metadata version 9160, and parity signer only have version 9130, 9150 and 9151.

![IMG_5030702DF15F-1](https://user-images.githubusercontent.com/1623359/155152322-6bf02682-ee00-4e1d-b424-687b6262ec29.jpeg)

**Comment by kirushik** [comment]
Please update the metadata in your Signer to the latest version, by scanning a "qr movie" available at https://metadata.parity.io/#/kusama
With Substrate-based chains allowing arbitrary change of the transaction parsing semantics between runtime/metadata versions, it's not possible to build a future-proof parser for transactions without having to go through the effort of updating every time there's a nontrivial runtime update.
Metadata updates are signed (meaning that you shouldn't worry too much about an authenticity of the "qr movie" you're scanning; you can also fork https://github.com/paritytech/metadata-portal/ and sign and publish your own metadata payloads without trusting Parity, or if you want to support some networks not currently handled by Parity.

**Comment by Slesarew** [comment]
It is also worth mentioning that metadata updates could be generated locally without having to maintain a portal, with use of https://github.com/paritytech/parity-signer/tree/master/rust/generate_message - this could be done by individual users or collectively (this is when metadata portal becomes useful tool). I recommend to sign updates with some reasonable key though, just to improve security against someone with physical access to Signer device - and the networks that are already signed in Signer could only be updated with the same key unless device is properly wiped; to remove certificate key from default built-in networks, you'll need to use "remove general verifier" button under "general verifier" menu. Hopefully, this should not be needed as Parity's metadata portal is entering production stage and keeps up-to-date metadata at all times.

**Comment by geastwood** [comment]
Thank you @kirushik and @Slesarew for the detailed answer and some explanation. By scanning the  **qr movie**, I'm able to successfully update the metadata for Kusama and complete the transaction within our app.

**Comment by geastwood** [comment]
> https://github.com/paritytech/metadata-portal/

Seems to be not accessible from outside org?

**Comment by geastwood** [comment]
@Slesarew can I read more on the design of parity signer, more specifically the role of certificate?

**Comment by Slesarew** [comment]
> @Slesarew can I read more on the design of parity signer, more specifically the role of certificate?

I'm afraid, the documentation for this is not ready yet. The idea is quite simple though - since metadata updates are just statically hosted on the web, it would be trivial for an adversary to swap them and make transacrions rendering incorrect. Certificate is pretty much another standard Substrate's crypto keypair, that is used by trusted party to sign update video just to prove that the payload was indeed generated by that party. As an additional security feature, Signer uses TOFU on these certificates and also includes a default built-in certificate issued by Parity (which could be removed and TOFU-replaced by any other certificate, although this requires full Signer wipe to secure device further from attacks based on physical access to the phone).Only default networks and network that were updated with default (general) certificate are bound to it, other networks could use individual certificates, although any change of certificates requires Signer wipe.

All this encourages some UX-oriented centralization, even though it does not enforce it (since, again, any user can sign everything in-house), I know it's not perfect.

Fortunately, certificates are now considered to be temporary measure until completely trustless on-chain verification of metadata is implemented: https://github.com/paritytech/parity-signer/issues/898.

**Comment by stephanie-olp** [comment]
Can't do anything in our side

**Comment by Slesarew** [comment]
> > https://github.com/paritytech/metadata-portal/
> 
> Seems to be not accessible from outside org?

should be public by now, please let me know if it isn't

**Comment by geastwood** [comment]
@Slesarew still not accessible. :(
